# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2

updates:
  - package-ecosystem: github-actions
    open-pull-requests-limit: 1
    commit-message: { prefix: chore(deps) }
    directory: '/'
    schedule:
      day: sunday
      interval: weekly
      timezone: Europe/Berlin
    groups:
      github-actions:
        patterns: [ '*' ]
    cooldown:
      default-days: 1
      include: [ '*' ]

  - package-ecosystem: 'docker'
    open-pull-requests-limit: 1
    commit-message: { prefix: security(deps) }
    directories: ['**/*']
    schedule:
      interval: daily
      timezone: Europe/Berlin
    groups:
      security:
        applies-to: security-updates
        update-types: [ minor, patch ]
        patterns: [ '*' ]
    ignore:
      - dependency-name: '*'
        update-types: [ 'version-update:semver-major' ]
