apiVersion: v2
type: application
name: sesamy-umami
description: Helm chart for the Sesamy Umami integration.
icon: https://avatars.githubusercontent.com/u/889755?s=200&v=4
home: https://www.foomo.org
keywords:
  - foomo
  - sesamy
sources:
  - https://github.com/foomo/helm-charts
annotations:
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/foomo/helm-charts/tree/main/charts/sesamy-umami
    - name: Umami Source
      url: https://github.com/umami-software/umami
version: 0.2.4
appVersion: 2.19.0
