apiVersion: v2
type: application
name: backups
description: Helm chart for backing things up.
icon: https://avatars.githubusercontent.com/u/889755?s=200&v=4
home: https://www.foomo.org
keywords:
  - foomo
  - backups
sources:
  - https://github.com/foomo/helm-charts
annotations:
  "artifacthub.io/links": |
    - name: Chart Source
      url: https://github.com/foomo/helm-charts/main/charts/backups

version: 0.1.3
appVersion: 0.1.3
